services:
  web:
    build: .
    image: backend_image
    container_name: backend_build_container
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "../env:/home/env"
    ports: 
      - "3000:3000"
      - "8080:8080"
