version: "3"
services:
  web:
    build: .
    image: production_build_image
    container_name: production_build_container
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "../env:/home/env"
    ports:
      - "80:80"